### ISSUE TITLE
ACF Cleaner doesn't work if plugin is bundled in a theme

### ISSUE THREAD

**Issue by coreyallen** [whatwedo/whatwedo-acf-cleaner#1]
If ACF is bundled with a theme, ACF Cleaner will display "Warning: You need to Activate Advanced Custom Fields in order to use whatwedo ACF Cleaner" despite ACF Pro being active and working.

**Comment by JiveDig** [comment]
Hey y'all. Theme dev here :)

First off, ACF Cleaner looks awesome! I wish (hope?) this was added to ACF core. Things can get messy after people change fields all the time.

Anyway, for this issue, we load ACF in the theme, but it's added via `plugins_loaded` hook so maybe too late for you, if your plugin checks `function_exists( 'get_field' )` prior to that.

Happy to help figure this out if we can. I'm going to try to get @coreyallen a workaround for now, but it'd be nice to know your plugin works with any theme (or other plugin) loading ACF this way.

**Comment by xarem** [comment]
Hi all!

This is true, it's because we check the availability of ACF with `function_exists` [here](https://github.com/whatwedo/whatwedo-acf-cleaner/blob/master/class/class-wp.php#L20).

I'm considering rewriting this and using `acf/init` hook or similar to add our scripts. But the downside is that we can't check if ACF is activated and show a warning to the users. 

Do you have a better idea? 

There is a simple workaround if it's urgent to fix it in your theme: you can just add this after ACF is loaded:
```php
new whatwedo\AcfCleaner\WP();
```

ping @marcwieland95

**Comment by JiveDig** [comment]
I like acf/init or do your class_exists( 'acf' ) || class_exists( 'acf_pro' ) checks inside of a hook on a later priority via plugins_loaded. 

If you go the acf/init route, that would only fire if ACF is active though, so I don't see any real downside to that way either.

**Comment by xarem** [comment]
> I like acf/init or do your class_exists( 'acf' ) || class_exists( 'acf_pro' ) checks inside of a hook on a later priority via plugins_loaded.

Good idea. Let's add a late `plugins_loaded` hook with class existence checking for the user warning and add the rest of the hooks within `acf/init`. 

@marcwieland95 what do you mean?

**Comment by JiveDig** [comment]
Just to clarify for the OP, we have a workaround already in place, so Corey is able to do what he needs to do. This issue will just help us both in the future if you can make some of these changes :)

**Comment by mawiswiss** [comment]
Thanks a lot for creating the **first** issue since we moved the repo to Github ;-)

The solutions sound absolutely reasonable and I'll fix the issue in that way once we have a couple of more things to solve.

**Comment by mawiswiss** [comment]
In the upcoming release, we don't load the plugin if ACF isn't activated (`acf/init` hook) and also show the message in case the plugin is required late (function check inside the `plugins_loaded` hook).

<img width="703" alt="CleanShot 2023-04-17 at 10 29 32@2x" src="https://user-images.githubusercontent.com/6168975/232371432-e8e246b1-4cc7-480a-9ba5-4c14fac9da44.png">
