### ISSUE TITLE
Warning: Undefined array key "__key" in /var/www/html/wp-content/plugins/whatwedo-acf-cleaner/class/class-discovery.php on line 89

### ISSUE THREAD

**Issue by melcarthus** [whatwedo/whatwedo-acf-cleaner#3]
I posted an issue earlier that got hot fixed 5 days ago. Same issue but for another field, now its __key, first is was __clone.

Kind regards,

Tim

**Comment by mawiswiss** [comment]
I saw this error just after I pushed the hotfix and fixed it as well. But as I can see now, the fix of the fix isn't tagged correctly on the WordPress plugin repo. Here in the master branch it's already fixed.

**Comment by melcarthus** [comment]
cool thanks!

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Marc Wieland ***@***.***>
Verzonden: Tuesday, May 30, 2023 5:07:23 PM
Aan: whatwedo/whatwedo-acf-cleaner ***@***.***>
CC: Tim Wolf ***@***.***>; Author ***@***.***>
Onderwerp: Re: [whatwedo/whatwedo-acf-cleaner] Warning: Undefined array key "__key" in /var/www/html/wp-content/plugins/whatwedo-acf-cleaner/class/class-discovery.php on line 89 (Issue #3)


I saw this error just after I pushed the hotfix and fixed it as well. But as I can see now, the fix of the fix isn't tagged correctly on the WordPress plugin repo. Here in the master branch it's already fixed.
