### ISSUE TITLE
Warning: Undefined array key

### ISSUE THREAD

**Issue by Agencelaboite** [whatwedo/whatwedo-acf-cleaner#4]
It's only been showing me these errors for a few days now. (2x the same one).

Warning: Undefined array key "__key" in /var/www/html/web/app/plugins/whatwedo-acf-cleaner/class/class-discovery.php on line 89
Warning: Undefined array key "__key" in /var/www/html/web/app/plugins/whatwedo-acf-cleaner/class/class-discovery.php on line 89

Thank you for all your hard work!

**Comment by mawiswiss** [comment]
This is a duplicate of #3.
If I remember correctly I already solved this issue. Just wondering why the ticket is still open. Are you on the most recent version of the plugin (`1.2.2`)?
