### ISSUE TITLE
List to be deleted keys

### ISSUE THREAD

**Issue by szepeviktor** [whatwedo/whatwedo-acf-cleaner#5]
How do I list post-ID and post-meta-ID pairs that will be deleted?
@marcwieland95

**Comment by szepeviktor** [comment]
BTW Do you plan to support WP-CLI?

**Comment by mawiswiss** [comment]
Hey @szepeviktor

It's a bit of a black box, and I never added any hooks or anything, developers could read to get an array of items which will get deleted.
From a user perspective, you can go to the post and scroll down to the metabox section. There, you see all the data listed and see what gets deleted. I wanted to create a proper output of the data on the options page, but never had time to develop it. There's a lot of data which has to be sorted and displayed in a structured way to make sense.

About WP CLI. I never thought about that and I haven't done much development recently. It's not on my timeline for now. But actually a feature which makes total sense and isn't that hard to implement.

Feel free to submit any pull requests. I'm happy to review it and implement it.

**Comment by szepeviktor** [comment]
Thank you.

I do not dare to push the red button without randomly checking some post meta.

**Comment by mawiswiss** [comment]
@szepeviktor I understand. I normally sync the database to my local instance, run the commands and test it.
If everything works, I run it on production as well.
